
- platform: broadlink
  host: !secret sensor_broadlink_ip
  mac: !secret sensor_broadlink_mac
  name: Home
  monitored_conditions:
    - 'temperature'

- platform: sql
  scan_interval: 2
  queries:
    - name: front door last opened
      query: "select last_changed from states where entity_id = 'binary_sensor.0x00158d000273bbe4_contact' and state = 'on' order by last_changed desc;"
      column: 'last_changed'
      value_template: "{{ as_timestamp(value~'+00:00') | timestamp_custom('%a %b %-d %-I:%M%p')}}"
    - name: living to garage door last opened
      query: "select last_changed from states where entity_id = 'binary_sensor.0x00158d000275ef5d_contact' and state = 'on' order by last_changed desc;"
      column: 'last_changed'
      value_template: "{{ as_timestamp(value~'+00:00') | timestamp_custom('%a %b %-d %-I:%M%p') }}"
    - name: garage door last opened
      query: "select last_changed from states where entity_id = 'binary_sensor.0x00158d00029bf0c3_contact' and state = 'on' order by last_changed desc;"
      column: 'last_changed'
      value_template: "{{ as_timestamp(value~'+00:00') | timestamp_custom('%a %b %-d %-I:%M%p')}}"
    - name: backgate last opened
      query: "select last_changed from states where entity_id = 'binary_sensor.0x00158d00029b063b_contact' and state = 'on' order by last_changed desc;"
      column: 'last_changed'
      value_template: "{{ as_timestamp(value~'+00:00') | timestamp_custom('%a %b %-d %-I:%M%p')}}"
    - name: kitchen door last opened
      query: "select last_changed from states where entity_id = 'binary_sensor.0x00158d000275f11d_contact' and state = 'on' order by last_changed desc;"
      column: 'last_changed'
      value_template: "{{ as_timestamp(value~'+00:00') | timestamp_custom('%a %b %-d %-I:%M%p')}}"
    - name: basement door last opened
      query: "select last_changed from states where entity_id = 'binary_sensor.0x00158d000273bb1d_contact' and state = 'on' order by last_changed desc;"
      column: 'last_changed'
      value_template: "{{ as_timestamp(value~'+00:00') | timestamp_custom('%a %b %-d %-I:%M%p')}}"
    - name: living room last motion
      query: "select last_changed from states where friendly_name = 'living_motion_occupancy' and state = 'on' order by last_changed desc;"
      column: 'last_changed'
      value_template: "{{ as_timestamp(value~'+00:00') | timestamp_custom('%a %b %-d %-I:%M%p')}}"
    - name: basement last motion
      query: "select last_changed from states where entity_id = 'binary_sensor.0x00158d00020dfca1_occupancy' and state = 'on' order by last_changed desc;"
      column: 'last_changed'
      value_template: "{{ as_timestamp(value~'+00:00') | timestamp_custom('%a %b %-d %-I:%M%p')}}"
    - name: garage last motion
      query: "select last_changed from states where entity_id = 'binary_sensor.garage_motion_occupancy' and state = 'on' order by last_changed desc;"
      column: 'last_changed'
      value_template: "{{ as_timestamp(value~'+00:00') | timestamp_custom('%a %b %-d %-I:%M%p')}}"
    - name: kitchen last motion
      query: "select last_changed from states where entity_id = 'binary_sensor.0x00158d00040590bd_occupancy' and state = 'on' order by last_changed desc;"
      column: 'last_changed'
      value_template: "{{ as_timestamp(value~'+00:00') | timestamp_custom('%a %b %-d %-I:%M%p')}}"
    - name: backgate last motion
      query: "select last_changed from states where entity_id = 'binary_sensor.0x00158d0003faf12c_occupancy' and state = 'on' order by last_changed desc;"
      column: 'last_changed'
      value_template: "{{ as_timestamp(value~'+00:00') | timestamp_custom('%a %b %-d %-I:%M%p')}}"
